### PR TITLE
DEV-22 - Swagger to slate markdown script for V3

### PR DESCRIPTION
**Pull request by bookernath**
#### What?

A script that will take raw Swagger files and convert them to slate-friendly markdown for easy including into the docs.

#### How To Test

Run `node swagger2md.js` from project root, with valid swagger .yaml files in source/api/v3

You should expect any .yaml.md files in the directory to be deleted and new generated files to be created in their place from the valid .yaml files.

Must `npm install` these first:
widdershins
js-yaml

The intent is that changes to the raw .yaml files can be committed, after which this script can be run and the updated .yaml.md files are then committed and deployed.

ping @bc-AlyssNoland @becomevocal

### CODE REVIEW

**Comment by bc-AlyssNoland** [comment]
@bookernath can we move the yaml files that it is generated off of into the data/ folder or into an asset/ folder. Currently, this would build them into a path that would get crawled by google.

**Comment by bookernath** [comment]
@bc-AlyssNoland done

**Comment by bc-mkatz** [comment]
@bookernath: We're using the existing assets/ [plural] subdirectory, correct? Thanks for all this.

**Comment by bc-AlyssNoland** [comment]
@bc-mkatz is there a specific reason that they would need to be there? I asked that they be placed in another location due to existing code organization.

**Comment by bc-mkatz** [comment]
@bc-AlyssNoland: I'd just like to avoid proliferating subdirectories under /slate/. Particularly, subdirectories with near-match names, like /assets/ vs. /asset/. If these working files will not reside under /slate/, this isn't an issue. I'm hoping to keep the CSS structure relatively flat for the same reason – easier maintenance, less confusion.

**Comment by bc-AlyssNoland** [comment]
@bookernath make one last change for me and I'll smash the merge button. 

Can you have the files include a line:
`layout: "layout"`

image

**Pull request merged**
